CC = mpicc
CFLAGS = -O3 -g -mkl -openmp -DMPI
SRC = src/debug.c src/diaginv.c src/isdom.c src/lpu.c src/ct.c src/mathsub.c src/mpi/iter.c src/mpi/jacobi.c src/mpi/main.c
DBG = -DDEBUG

all :
	$(CC) $(CFLAGS) $(SRC) -o bin/jacobi_mpi

debug :
	$(CC) $(CFLAGS) $(DBG) $(SRC) -o bin/jacobi_mpi
	
clean :
	rm -rf bin
	mkdir bin
